module.exports = {
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_REQUEST_SUCCESS: 'USER_LOGIN_REQUEST_SUCCESS',
    USER_LOGIN_REQUEST_FAILURE: 'USER_LOGIN_REQUEST_FAILURE',
    USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
    USER_LOGOUT_REQUEST_SUCCESS: 'USER_LOGOUT_REQUEST_SUCCESS',
    USER_LOGOUT_REQUEST_FAILURE: 'USER_LOGOUT_REQUEST_SUCCESS',
    USER_REPOSITORIES_FETCHING: 'USER_REPOSITORIES_FETCHING',
    USER_REPOSITORIES_FETCHING_SUCCES: 'USER_REPOSITORIES_FETCHING_SUCCES',
    USER_REPOSITORIES_FETCHING_FAILURE: 'USER_REPOSITORIES_FETCHING_FAILURE',
    USER_REPOSITORY_ISSUE_CREATE: 'USER_REPOSITORY_ISSUE_CREATE',
    USER_REPOSITORY_ISSUE_CREATE_SUCCESS: 'USER_REPOSITORY_ISSUE_CREATE_SUCCESS',
    USER_REPOSITORY_ISSUE_CREATE_FAILURE: 'USER_REPOSITORY_ISSUE_CREATE_FAILURE'
};
